#ifndef ROBOTMAP_H_
#define ROBOTMAP_H_

#define COMPRESSOR_PRESSURE 2
#define COMPRESSOR_RELAY 1
#define INTAKE_MOTOR 6
#define INTAKE_RELAY 5
#define SHOOTER_MOTOR 4
#define SHOOTER_RELAY 6
#define DRIVE_LEFT_MOTOR 1
#define DRIVE_RIGHT_MOTOR 10
#define GEARSHIFT_RELAY 2

#endif /* ROBOTMAP_H_ */
